rust: macros: rewrite `#[vtable]` using `syn`
Now that `syn` and `quote` are available in the Kernel use them for the
`#[vtable]` proc-macro attribute instead of the current string based
proc-macro approach.

Proc-macros written using `syn` are a lot more readable and thus easier
to maintain than proc-macros written using string manipulation. An
additional advantage of `syn` is the improved error reporting, here is
an example:

    #[vtable]
    const _: () = ();

Prior to this patch, the error reads:

    error: custom attribute panicked
      --> samples/rust/rust_minimal.rs:40:1
       |
    40 | #[vtable]
       | ^^^^^^^^^
       |
       = help: message: #[vtable] attribute should only be applied to trait or impl block

    error: aborting due to 1 previous error

After this patch, the error reads:

    error: `#[vtable]` expects a `trait` or `impl`.
      --> samples/rust/rust_minimal.rs:41:1
       |
    41 | const _: () = ();
       | ^^^^^^^^^^^^^^^^^

    error: aborting due to 1 previous error

Signed-off-by: Benno Lossin <benno.lossin@proton.me>